### ISSUE TITLE
Implement code to launch pi imager on Windows 10

### ISSUE THREAD

**Issue by asurirk** [cloudmesh/cloudmesh-pi-cluster#110]
Below script launches pi imager on Windows 10

import subprocess
cmd = ([r'C:\Program Files (x86)\Raspberry Pi Imager\rpi-imager.exe'])
subprocess.run(cmd)

**Comment by laszewsk** [comment]
is this completed?

**Comment by laszewsk** [comment]
if not add tu ubuntu branch

**Comment by laszewsk** [comment]
pleaase add url where code change has been made so i can review
