### ISSUE TITLE
(Anthony) trivial/medium: network scannng on pi and laptops

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#121]
- [x] nmap
- [x] arp
- [ ] scapy: https://jupyterhub.readthedocs.io/en/stable/quickstart.html
- [x] ping
- [x] traceroute
- [ ] snort (?)

**Comment by aporlowski** [comment]
Link here

https://cloudmesh.github.io/pi/tutorial/network-scanning-tutorial/
