### ISSUE TITLE
Anthony: trivial: user managernt

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#124]
- [x] use the cloudmesh comamnds to create users on hosts. 
- [x] see https://www.raspberrypi.org/documentation/linux/usage/users.md how to do it on a single host
- [x] develop command cms host adduser --publickey ...
- [x] develop command cms host deleteuser 
- [x] cms scatter to username when user is not used its ubuntu/pi dependent on --os flag?
- [x] make proposal for command discuss with all. send url

https://cloudmesh.github.io/pi/tutorial/usermanagement/

**Comment by aporlowski** [comment]
https://cloudmesh.github.io/pi/tutorial/usermanagement/
