### ISSUE TITLE
github write access

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#22]
All need to accept the invitations form github. There are so far the following repos. As you will have direct write access, please be careful. Often using a branches good. But coordinate first with all of us as they may work in parallel. Please check of if you have accepted the invitations (not just this repo, see the three others)

github ids

- [x] aporlowski
- [x] rickotten
- [x] dkkolli
- [x] asurirk
- [ ] armathur123   (needs an additional meeting, possibly just pull requests)

Repos

- cloudmesh-inventory
- cloudmesh-pi-burn
- cloudmesh-pi-cluster
- others can be accessed for now with pull request

Do you all have knowledge in branches and github in general

**Comment by asurirk** [comment]
@laszewsk I have used Git and other version control tools. I know how to use GitHub.
