### ISSUE TITLE
clloudmesh.util.sudo_writefile

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#33]
https://github.com/cloudmesh/cloudmesh-common/issues/20

**Comment by laszewsk** [comment]
was this completed? have docstrings be added, is it in cloudmesh.common, have duplicated code been removed?

**Comment by aporlowski** [comment]
I fixed the left over tmp file. Pull request to common is [https://github.com/cloudmesh/cloudmesh-common/pull/23](https://github.com/cloudmesh/cloudmesh-common/pull/23 ). This bug can be closed after pull.

sudo_readfile, sudo_writefile, readfile, and writefile have all been removed from burn util.py

The only reference to burn readfile and writefile left were in Image.py. I changed those to common.util and the unit tests pass.
