### ISSUE TITLE
--cmdline=FLAGS

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#38]
Richie or Anthony can modify the burn program to add the new --sdcard flag to deal with the 1.8v issue

find how to do that in slack and add to comment

- [ ] benchmark create tutorial
- [x] sdhci.quirks2=4 at end of cmdline.txt

- [ ] this need to be added to burn and pi commands. The burn does it on an USB sd card the pi does it to the currently running sdcard, and can only be executed on a pi

slack
- https://cloudmesh-community.slack.com/archives/CTP848QDV/p1611004778126700
- https://cloudmesh-community.slack.com/archives/CTP848QDV/p1611004778126700
- https://cloudmesh-community.slack.com/archives/CTP848QDV/p1610827349046300
- https://cloudmesh-community.slack.com/archives/CTP848QDV/p1610826551034700
- how do i set it back: remove it from cmdline.txt and reboot 

8:23 PM
Anthony Orlowski That was set in cmdline.txt in /boot. So it won't be there on a freshly burned card

**Comment by laszewsk** [comment]
Anthony do you remember what the command was that we needed to add?

**Comment by laszewsk** [comment]
sdhci.quirks2=4

**Comment by aporlowski** [comment]
Implemented and documented  `cms burn set --cmdline=CMDLINE`. Added example to force 3.3V sd card operation to fix sd card extender.

https://github.com/cloudmesh/cloudmesh-pi-burn/commit/2b1fcc058782cb3a94e3bd828cba3e67fa8c4f6d
