### ISSUE TITLE
BUG: dd command on PI

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#43]
- [x] review Gregor's dd command on Linux
- [x] evaluate if this command can be used on the PI
- [x] if so integrate
- [x] fsync seems to be missing

- [x] we may want to add an option in general progress=True that when tru the status=progress is set.

**Comment by laszewsk** [comment]
can you update issus

**Comment by aporlowski** [comment]
Closed:
https://github.com/cloudmesh/cloudmesh-pi-burn/commit/12fae15c7668b31d795df7f97a1a788c18b3ea8b
