### ISSUE TITLE
BUG: too short key

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#47]
- [x] evaluate if this code is still needed

if True:
    ##############################################
    #
    # Ignore on pi:  DH KEY TOO SMALL
    #
    # see: https://stackoverflow.com/questions/38015537/python-requests-exceptions-sslerror-dh-key-too-small
    #

    requests.packages.urllib3.disable_warnings()
    requests.packages.urllib3.util.ssl_.DEFAULT_CIPHERS = 'AES128-SHA'
    try:
        # noinspection PyPep8
        requests.packages.urllib3.contrib.pyopenssl.DEFAULT_SSL_CIPHER_LIST = 'AES128-SHA'
    except AttributeError:
        # no pyopenssl support used / needed / available
        pass

    #
    ##############################################

**Comment by aporlowski** [comment]
No longer needed. Images download fine without.

https://github.com/cloudmesh/cloudmesh-pi-burn/commit/e61a83a4a61bf45b493d9fe4b5fa890e4db7014e

**Comment by laszewsk** [comment]
code not needed
