### ISSUE TITLE
BUG: duplicated wifi

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#57]
-  [x] there is code in a file wifi.py in cloudmesh-pi-cluster/cloudmesh
   https://github.com/cloudmesh/cloudmesh-common/blob/main/cloudmesh/common/wifi.py
- [x] remove from cluster and us wifi methods from pi burn. Potentially fix code in burn if needed.
- [x] verify that the code in cloudmesh.common.wifi works Gregor has not tested it, fix if needed

- [x] verify with Richie whay it is duplicated
- [x] evaluate if this code duplicates code in cloudmesh burn
- [x] develop a unit test for wifi

The wifi classes need to be merged.

- [x] code has been mofed and improved in cloudmesh.common.wifi. THis corrects a,b,c

  * a) cloudmesh.pi.wifi has incomplete template, see cloudmesh.brun.burner for a more complete template
  * b) Although i like the wifi to be in cloudmesh.pi.burn, it has the disadvantage that we introduce recursive dependencies.
     we could move it to cloudmesh.common.wifi and both woudl use it
  * c) once its moved to cloudmesh.common.wifi.py, we update both codes to use that new method.

- [x] Gregor removed:   .replace("BEGIN", "{").replace("END", "}"), seems like that in anolder version of teh code we did not use {{ or }} but BEGIN END INSTEAD, so this can be removed

**Comment by laszewsk** [comment]
there is code in pi cluster and pi burn related to wifisetup. The code in pi cluster is likely duplicated. We can leverage the code form pi burn and call that as a method. There is no reason to have tow methods that do the same but aer in different repos duplicated.

**Comment by rickotten** [comment]
Integrated cloudmesh.common.wifi into configure_wifi in burner.py. [Commit](https://github.com/cloudmesh/cloudmesh-pi-burn/commit/7b7567cde900b439787e5c2ed8f6ef9e93d2dc83)
