### ISSUE TITLE
Bug: usb.py

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#58]
cloudmesh/burn/usb.py:70:35: F821 undefined name 'vendor'

**Comment by aporlowski** [comment]
Closed:
[https://github.com/cloudmesh/cloudmesh-pi-burn/commit/ef850aa6658f225147f7423a274e6c951de12233](https://github.com/cloudmesh/cloudmesh-pi-burn/commit/ef850aa6658f225147f7423a274e6c951de12233)
[https://github.com/cloudmesh/cloudmesh-pi-burn/commit/9058308a2372e85916c35f551830a47933144eb9](https://github.com/cloudmesh/cloudmesh-pi-burn/commit/9058308a2372e85916c35f551830a47933144eb9)
[https://github.com/cloudmesh/cloudmesh-pi-burn/commit/111d75c2f3d5e46eeb7def6ba1bc036c546036b9](https://github.com/cloudmesh/cloudmesh-pi-burn/commit/111d75c2f3d5e46eeb7def6ba1bc036c546036b9)
[https://github.com/cloudmesh/cloudmesh-pi-burn/commit/e22af57087418330a161c6360a781afe8aeec7b0](https://github.com/cloudmesh/cloudmesh-pi-burn/commit/e22af57087418330a161c6360a781afe8aeec7b0)
