### ISSUE TITLE
Bug: image.py

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#59]
- [x] cloudmesh/burn/image.py:165:33: F821 undefined name 'source_url'
- [x] cloudmesh/burn/image.py:165:33: F821 undefined name 'source_url'
- [x] cloudmesh/burn/image.py:196:13: F841 local variable 'image_path' is assigned to but never used
- [x] cloudmesh/burn/image.py:204:9: F841 local variable 'size' is assigned to but never used. Size should be used to verify downloaded file (low priority)

**Comment by aporlowski** [comment]
Complete:

https://github.com/cloudmesh/cloudmesh-pi-burn/commit/1ac929955ba3128fbb72666f80448aec29101764
https://github.com/cloudmesh/cloudmesh-pi-burn/commit/a54a97b7b30c0713d70ed2405971140031be8dd0
