### ISSUE TITLE
Verify get/main/pi/index.html and remove beta from README before release.

### ISSUE THREAD

**Issue by aporlowski** [cloudmesh/cloudmesh-pi-cluster#70]
pi@managerpi:~ $ curl -Ls http://cloudmesh.github.io/get/pi | sh
                # see note use different link for now
```
TODO: Remove this if not needed.

Note: at present we are still improving the pi script and thus you
should for now use the command

```
pi@managerpi:~ $  curl -Ls https://raw.githubusercontent.com/cloudmesh/get/main/pi/index.html | sh 
```

**Comment by laszewsk** [comment]
removes and added missing - after sh
