### ISSUE TITLE
Write a Python script to compare SHA to make sure SD card burn without errors.

### ISSUE THREAD

**Issue by asurirk** [cloudmesh/cloudmesh-pi-cluster#72]
- [x] write prg
  - [x] Gregor implemented download of sha files as we needed to verify if download works
  - [x] still missing the actual comparision 
- [x] integrate in cloudmesh-pi-burn Image def verify(file=None)

**Comment by laszewsk** [comment]
I had to make sure the download works, so I quickly implemented it so others are not affected.

**Comment by laszewsk** [comment]
I had to make sure the download works, so I quickly implemented it so others are not affected.
