### ISSUE TITLE
Cloudmesh Pi Burn GUI

### ISSUE THREAD

**Issue by asurirk** [cloudmesh/cloudmesh-pi-cluster#82]

**Comment by asurirk** [comment]
**[Notes from Gregor]([url]([url](url
<img width="473" alt="screenshoot" src="https://user-images.githubusercontent.com/45571241/107882934-eed6ed00-6eb9-11eb-8ae2-f4b63ef42937.png">
)))**
All: if someone enjoys putting a littel GUI in front of the command. I have experimented and settled on PySimpleGUI. we used that befor and its reasonably wel suited for what we want it for.
I put experimental code in cloudmesh-pi-burn/experimental
Its super rough, and has no functionality, i just wanted to see if we have all elements including a file browser

**Comment by asurirk** [comment]
**Gregor's input on the implementation**

@Rama Asuri on teh gui side this we need to first generate the command that needs to be executed (cms burn create …) via the GUI.
the important part is that there could be multiple USB devices in the USB ports, we should interrupt if we find more than one.
Please note that we need to identify if we have /dev/sda, /dev/sdb, /dev/disk2, …
the way i do it in the gui template is wrong as i simply probe for mounted filesystems instead of available usb devices, In principal we have that function somewhere :wink: but I forgot what it actually is.
You will have to look at the code to identify that
Also for the selection of the image we want to be able to add “tags” or a filename with browse.
We also need to download the image if the tag is not available.
While evaluating the various GUI frameworks the one in the current example seems best. The documentation is not as good as it coudl be for it, but you find many examples on the internet.
make sure to see if you can align the labels and the entryes in a grid so they look more professional. I have done this previously, maybe
gui.SetOptions(text_justification=‘right’) woudl solve that?
11:39
Once you figure out the command we can just call it in an event via os.system
An improved version could eb done that redirects the output but thsi does require a change in the code wher ethe sudo password is queried and actally passed to the commands.
As that change is a bit more involved,
I do recommend that in that second phase after you figured out the layout of the gui and developed dummy print command statements for the events
we do a new branch called - first password -> this will change the current code to enter the sudo password at the beginning and than reuses it in the commands.
and than anothe branch gui after we verified the first works cakked gui.
11:40
The reason this is a bit more complex than one woudl think is the use of the sudo passwords

**Comment by asurirk** [comment]
1. Add total bun time.
2. Create a design document

**Comment by laszewsk** [comment]
stick with pysimple gui

**Comment by laszewsk** [comment]
it would be cool to have a checkbox that gets updated for each sd card we burn, e.g. a status

def set_status(name="red", status="done")
we have status=fail, done, in progress

we coudl start simple via text labels that we manipulate,but coudl also do circle images later

**Comment by laszewsk** [comment]
see new example in experimental

fake.py | progress.py

this way we can do a progress window, we still need additional information such as 

eta, and so on provided by pv or tqdm
