### ISSUE TITLE
figure out the issue in /etc/hosts

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#85]
see the pberrypi

```
127.0.0.1       localhost
::1             localhost ip6-localhost ip6-loopback
ff02::1         ip6-allnodes
ff02::2         ip6-allrouters

127.0.1.1 red
pberrypi
10.0.0.1        red
10.0.0.2        red01
10.0.0.3        red02
```

**Comment by aporlowski** [comment]
I am going to guess the issue is somewhere in this code from set_hostname() in burner.py

` if not self.dryrun:
            # with open(f'{mountpoint}/etc/hosts', 'r') as f:  # read /etc/hosts
            f = sudo_readfile(f'{mountpoint}/etc/hosts')
            # lines = [l for l in f.readlines()][:-1]  # ignore the last line
            lines = f[:-1]
            newlastline = '\n127.0.1.1 ' + hostname + '\n'

        if not self.dryrun:
            new_hostsfile_contents = '\n'.join(lines) + newlastline
            sudo_writefile(f'{mountpoint}/etc/hosts', new_hostsfile_contents)`

**Comment by laszewsk** [comment]
looks like the writefile does not work properly in ext4 on macOS
I have replaced it with a pipe to /dev/sdtin

also on osc we do not actually need sudo ...
