### ISSUE TITLE
file permissions

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#89]
ANthony and Richard. This is importan, but others can help as it involves just booting and looking. Please notify if somone takes on the task in the comments

Who is working on it:

- [ ] Richie
- [ ] Adam
- [ ] DK
- [ ] Rama
- [x] Anthony

- [x] /etc/systemd/system/sshd.service
   does not exist when we burn with imager we need to verify what it does. I think it may be generated at first boot, but i think we actually write it to disc, is this even needed?

- [x] /etc/passwd
- [x] /etc/ssh/sshd_config

We need confirmation that the following permissions are ok. Please burn vanilla image with imager, boot and check what permisisons are. remember we have fix_permissions, we also need to verify if 777 is the right permission for scripts started on system level via rc.local

```
                ["/etc/default/keyboard", 0, 0, 0o644],
                ["/boot/fix_permissions.py", 0, 0, 0o777],
                ["/boot/ssh", 0, 0, 0o777],
                ["/boot/wpa_supplicant.conf", 0, 0, 0o600],
                ["/etc/hosts", 0, 0, 0o644],
                ["/etc/passwd", 0, 0, 0o644],
                ["/etc/dhcpcd.conf", 0, 109, 0o664],
                ["/etc/hostname", 0, 0, 0o644],
                ["/etc/ssh/sshd_config", 0, 0, 0o644],
                ["/etc/shadow", 0, 0, 0o600],
                ["/etc/rc.local", 0, 0, 0o751],
                ["/home/pi/.ssh", 1000, 1000, 0o700],
                ["/home/pi/.ssh/authorized_keys", 1000, 1000, 0o644],
                ["/home/pi/.ssh/id_rsa", 1000, 1000, 0o600],
                ["/home/pi/.ssh/id_rsa.pub", 1000, 1000, 0o644]
```

**Comment by aporlowski** [comment]
/etc/systemd/system/sshd.service is created on the first boot if a file names ssh is found in /boot on the sdcard.

We don't need to worry about its permissions

**Comment by aporlowski** [comment]
```
anthony@anthony-ubuntu:/media/anthony$ ls -aln ./rootfs/etc/default/keyboard 
-rw-r--r-- 1 0 0 150 Jan 11 07:54 ./rootfs/etc/default/keyboard
```

**Comment by aporlowski** [comment]
Only needed change I see is

/etc/shadow change to ["/etc/shadow", 0, 42, 0o640],

**Comment by aporlowski** [comment]
Fixed.

Commit.

https://github.com/cloudmesh/cloudmesh-pi-burn/commit/202e715f1b66aea2e13e8b6a5c5550ed41c98daa

Closing
