### ISSUE TITLE
Setting up keys on pi cluster

### ISSUE THREAD

**Issue by RhondaFischer** [cloudmesh/cloudmesh-pi-cluster#9]
After updating cloudmesh-installer and installing pi...
(ENV3) pi@yellow:~ $ cms host key create yellow,yellow-001
+------------+---------+--------------------------------------------------+
| host | success | stdout |
+------------+---------+--------------------------------------------------+
| yellow | True | ssh-rsa |
| | | pi@yellow |
| yellow-001 | False | |
+------------+---------+--------------------------------------------------

After ssh-add command
(ENV3) pi@yellow:~/cm $ cms host key create yellow,yellow-001
+------------+---------+--------+
| host       | success | stdout |
+------------+---------+--------+
| yellow     | False   |        |
| yellow-001 | False   |        |
+------------+---------+--------+

(ENV3) pi@yellow:~/cm $ cms host key list yellow,yellow-001
+------------+---------+--------+
| host       | success | stdout |
+------------+---------+--------+
| yellow     | False   |        |
| yellow-001 | False   |        |
+------------+---------+--------+

**Comment by laszewsk** [comment]
gregor implementate gather scatter
