### ISSUE TITLE
use yn_choice

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#93]
This is now a bug as it prevents me to implement the -y option easily

line: ~1800

please replace logic and use 

yn_choice

      if i < len(hostnames) - 1:
                if (i + 1) != ((i + 1) % len(keys)):
                    choice = input(
                        f"Slot {keys[(i + 1) % len(keys)]} "
                        "needs to be reused. Do you wish to continue? [y/n] ")
                    while (choice != 'y') and (choice != 'n'):
                        choice = input("Please use [y/n] ")
                    if choice == 'n':
                        break
                    elif choice == 'y':
                        input('Insert next card and press enter...')
                print('Burning next card...')
                print()

**Comment by laszewsk** [comment]
has this been completed?

**Comment by rickotten** [comment]
Completed.
