### ISSUE TITLE
Benchmarks

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#94]
This isssue is duplicated from #52 Please add your numbers there. I will do it for you and now close this one.. 

Imager tasks can be done by DK, Adam, Rama, you can also use this to confirm you r burn, and provide the infor from the benchmark, when you for example burn a cluster with 1 master and 1 worker. We need to verify who has which sdcard writer.

- [x] Adam
- [ ] Richie
- [ ] Anthony
- [ ] DK
- [ ] Rama

you need to include which SDCard burner you have. cms burn info will tell you. Also look at the parts list in piplanet and if its not listed there we need to list

- [x] burn imager (light)
- [ ] burn imager (full)
- [ ] burn ubuntu (64bit)
- [x] burn based on cms burner (full)
- [ ] burn based on cms burner (light)

**Comment by adamint** [comment]
Time to image master: 6:28
Time to install cloudmesh on master: 6:43
worker sd card says generic storage device, 64 GB
Time to burn worker on master: 2 minutes

**Comment by laszewsk** [comment]
This issue is a duplicate of this is #52. pleas add your values to the table

We like to close this issue
