### ISSUE TITLE
enable password and make default behavior as we need sudo

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-cluster#97]
branch password

- [x] add to inventory command
- [x] add to cluster command

have additional option to switch off password

I think we need a password to do modifications to the desktop if we use full and not light. Can we work on setting the password via a getpass and use that for setting up the burn?
THis seems real important and I think this prevents a release. Please discuss if we need password or not.
I think we can use sudo from the commandline without password (?) but I believe that the desktop has a build in feature that requires us to use password.
however i found we can set it via raspi-config but not passwd

Should the be only done on master or also workers?

Some ideas how we can change the passwd from commandline:
https://www.systutorials.com/changing-linux-users-password-in-one-command-line/

* [ ] document sudo passwd pi

**Comment by rickotten** [comment]
Added `--passwd` option to inventory burn.

**Comment by laszewsk** [comment]
can you also add to cluster command

**Comment by aporlowski** [comment]
I will add it to cluster

**Comment by aporlowski** [comment]
added --set_passwd to cluster

https://github.com/cloudmesh/cloudmesh-pi-burn/commit/3119b2c89c3a24355fef13ef0263b5f699cd507a

**Comment by aporlowski** [comment]
documented how to set password

https://github.com/cloudmesh/cloudmesh-pi-burn/commit/d0f624eb349a73a1e3a146fd02037f0f1a9c43a4#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
